name: Security checks

on: 
  push:
  pull_request:
  schedule:
    - cron: 0 0 1 * * # Every month

jobs:

  scan-cloudformation:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Configure python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      -
        name: Install CFRipper
        run: pip install cfripper
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Scan with CFRipper
        run: cfripper ./stacks/*.yaml --resolve